project:
  type: website

website:
  title: "MAS 261"
  navbar:
    left:
      - href: index.qmd
        text: This website provides access to MAS 261 lecture slides, notes, and R code files, regardless of access to Blackboard.

format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: visual



